version: '3.4'

services:
  dotnetexperiments.web:
    image: ${DOCKER_REGISTRY-}dotnetexperimentsweb
    build:
      context: .
      dockerfile: DotNetExperiments.Web/Dockerfile
  dotnetexperiments.api:
    image: ${DOCKER_REGISTRY-}dotnetexperimentsapi
    build:
      context: .
      dockerfile: DotNetExperiments.API/Dockerfile